---
#- name: Copy enviroment variables to remote host.
  #  hosts: localhost
  #  gather_facts: false
  #  check_mode: no
- hosts: all
  user: vagrant
  become: yes
  roles:
          - role: roles/tomcat
